# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Commands

# serve local:
# bash -c "bundle exec jekyll serve --future --drafts --livereload --incremental --config _config.yml,_config_staging.yml"

# build for development:
# bash -c "bundle exec jekyll build --future --drafts"

# build for production:
# bash -c "bundle exec JEKYLL_ENV=production jekyll build"


# Install everything for windows 10

# - git, code, ...
# - Windows Features: +Windows-Subsystem for linux (Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux)
# - Windows Store: +Ubuntu ( https://www.microsoft.com/store/productId/9NBLGGH4MSV6 )
# - start ubuntu, wait for initial setup, follow user setup
# - update packages: sudo apt-get update -y && sudo apt-get upgrade -y
# - install jekyll https://jekyllrb.com/docs/windows/
#    - sudo apt-add-repository ppa:brightbox/ruby-ng
#    - sudo apt-get update
#    - sudo apt-get install ruby2.6 ruby2.6-dev build-essential dh-autoreconf
#    - sudo gem update    (in blog folder)
#    - sudo gem install bundler    (in blog folder)
#    - sudo gem install jekyll --pre    (in blog folder)
#    - sudo apt install nodejs
#    - choco install webp


# - gem install jekyll fails? try (not needed for last fresh install run)
#      sudo apt install clang make ruby-all-dev libffi-dev
#      sudo gem install ffi

title: Fabse.net - Heimwerken, Elektronik, Basteln
email: fabse@fabse.net
lang: de
author: Fabian Wetzel
port: 4002
description: > # this means to ignore newlines until "baseurl:"
  Dieser Blog begleitet textuell meinen YouTube-Kanal und bietet weitere Inhalte sowie aktualisierte Inhalte, sofern notwendig.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fabse.net" # the base hostname & protocol for your site, e.g. http://example.com
#github_username:  jekyll
instagram_username: fabsenet
twitter_username: fabsenet
youtube_username: fabsenet
youtube_channel: FabseNetDe

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d.%m.%Y"

permalink: /:categories/:year/:month/:day/:title/

disqus:
  shortname: fabsenet

excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-minifier

jekyll-minifier:
  exclude: 'feed.xml'
  remove_intertag_spaces: true
  uglifier_args:
    harmony: true
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.txt
  - webp.ps1
  - azure-pipelines.yml

include:
  - .well-known

strict_front_matter: true

isstageconfig: false