# Jekyll site
# Package your Jekyll site using the jekyll/builder Docker container image.
# Add steps that build, test, save build artifacts, deploy, and more:
# https:///

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: Docker@0
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'LILMACOF231 (MASTER / PRODUCTION)'
  inputs:
    containerRegistryType: 'Container Registry'
    action: 'Run an image'
    imageName: 'jekyll/builder:latest'
    volumes: |
      $(build.sourcesDirectory):/srv/jekyll
      $(build.binariesDirectory):/srv/jekyll/_site
    containerCommand: 'jekyll build'
    detached: true

- task: Docker@0
  condition: not(eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Run Jekyll (STAGING, $(Build.SourceBranchName))'
  inputs:
    containerRegistryType: 'Container Registry'
    action: 'Run an image'
    imageName: 'jekyll/builder:latest'
    volumes: |
      $(build.sourcesDirectory):/srv/jekyll
      $(build.binariesDirectory):/srv/jekyll/_site
    containerCommand: 'bash -c "jekyll build --trace --config _config.yml,_config_staging.yml"'
    detached: true

# Publish Pipeline Artifact
# Publish a local directory or file as a named artifact for the current pipeline.
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'drop' 
    targetPath: $(build.binariesDirectory)
